# -*- coding: utf-8 -*-
"""Primeira_Pratica_RafaelaFreitas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ge2d0_RSRQ589J4xld-0mP13Lzjjf6B3
"""

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

operacao = input("Escolha a operação (+, -, *, /): ")

if operacao == "+":
    resultado = num1 + num2

elif operacao == "-":
    resultado = num1 - num2

elif operacao == "*":
    resultado = num1 * num2

elif operacao == "/":
    if num2 != 0:
        resultado = num1 / num2
    else:
        resultado = "Não é possível dividir por zero"

print("Resultado:", resultado)